version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongodb_data:/data/db

  go-logger:
    build: 
      context: .
      dockerfile: ./build/Dockerfile
    container_name: go-logger
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:1234@mongodb:27017/
    ports:
      - "8087:8087" 

volumes:
  mongodb_data:
